runner:
  client:
    config:
      genesis:
        besu: https://gist.githubusercontent.com/skylenet/4b133e10e3c5743752c7006a31d938d3/raw/23d5fcb536f2527c583eab93573558f2c60aeef7/genesis-mainnet-24350000-amsterdam-besu.json
        erigon: https://gist.githubusercontent.com/skylenet/83d6a3c1c8847badbabe6254fc286e45/raw/4546381a22e6c14a5c6fe0445106d8e31a91506f/genesis-mainnet-24350000-amsterdam-genesis.json
        geth: https://gist.githubusercontent.com/skylenet/83d6a3c1c8847badbabe6254fc286e45/raw/4546381a22e6c14a5c6fe0445106d8e31a91506f/genesis-mainnet-24350000-amsterdam-genesis.json
        nethermind: https://raw.githubusercontent.com/ethpandaops/perf-devnets/refs/heads/master/network-configs/devnet-2/metadata/chainspec.json
        reth: https://gist.githubusercontent.com/skylenet/83d6a3c1c8847badbabe6254fc286e45/raw/4546381a22e6c14a5c6fe0445106d8e31a91506f/genesis-mainnet-24350000-amsterdam-genesis.json
