runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: mainnet-24350000-amsterdam-compute
          chain: mainnet
          block: "24350000"
          test-type: compute
          context: repricing
          fork: amsterdam
      source:
        archive:
          # NOTE: 1.0.0 mainnet tests are broken and 1.1.0 has no tests
          file: https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v1.1.0/generated-tests-compute-mainnet.tar.gz
          pre_run_steps:
            - "repricings_compute/mainnet/gas-bump.txt"
            - "repricings_compute/mainnet/funding.txt"
          steps:
            setup:
              - "repricings_compute/mainnet/setup/*.txt"
            test:
              - "repricings_compute/mainnet/testing/*.txt"
        opcode_source:
        file: https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v1.1.0/opcodes_tracing-compute-mainnet.json

  container_runtime: podman
  client:
    config:
      rollback_strategy: none
