runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-3-24358000-amsterdam-compute
          chain: perf-devnet-3
          block: "24358000"
          test-type: compute
          context: repricing
          fork: amsterdam

      source:
        archive:
          file: https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v4.0.0/generated-tests-compute-perf-devnet-3.tar.gz
          pre_run_steps:
            - "repricings_compute/perf-devnet-3/gas-bump.txt"
            - "repricings_compute/perf-devnet-3/funding.txt"
          steps:
            setup:
              - "repricings_compute/perf-devnet-3/setup/*.txt"
            test:
              - "perf-devnet-3/testing/*.txt"
      opcode_source:
        file: https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v4.0.0/opcodes_tracing-compute-perf-devnet-3.json


  container_runtime: podman
  client:
    config:
      rollback_strategy: none
