runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-3-24358000-compute
          chain: perf-devnet-3
          block: "24358000"
          test-type: compute
          context: bal
          fork: amsterdam
      source:
        archive:
          file: https://github.com/NethermindEth/gas-benchmarks/actions/runs/23847558369/artifacts/6222084759
          pre_run_steps:
            - "perf-devnet-3/gas-bump.txt"
            - "perf-devnet-3/funding.txt"
          steps:
            setup:
              - "perf-devnet-3/setup/*.txt"
            test:
              - "perf-devnet-3/testing/*.txt"
          opcodes_file: https://github.com/NethermindEth/gas-benchmarks/actions/runs/23847558369/artifacts/6222074312
          opcodes: "opcodes_tracing.json"
