runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-3-24358000-amsterdam-stateful
          chain: perf-devnet-3
          block: "24358000"
          test-type: stateful
          context: repricing
          fork: amsterdam
      #source:
      #  archive:
      #    parts:
      #      - https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v1.1.0/generated-tests-stateful-perf-devnet-3.tar.gz.00.part
      #      - https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v1.1.0/generated-tests-stateful-perf-devnet-3.tar.gz.01.part
      #    pre_run_steps:
      #      - "repricings_stateful/perf-devnet-3/gas-bump.txt"
      #      - "repricings_stateful/perf-devnet-3/funding.txt"
      #    steps:
      #      setup:
      #        - "repricings_stateful/perf-devnet-3/setup/*.txt"
      #      test:
      #        - "repricings_stateful/perf-devnet-3/testing/*.txt"
      #opcode_source:
      #  file: https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v1.1.0/opcodes_tracing-stateful-perf-devnet-3.json

      source:
        archive:
          file: https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v3.1.0/generated-tests-stateful-perf-devnet-3.tar.gz
          pre_run_steps:
            - "repricings_stateful/perf-devnet-3/gas-bump.txt"
            - "repricings_stateful/perf-devnet-3/funding.txt"
          steps:
            setup:
              - "repricings_stateful/perf-devnet-3/setup/*.txt"
            test:
              - "perf-devnet-3/testing/*.txt"
      opcode_source:
        file: https://github.com/NethermindEth/gas-benchmarks/releases/download/amsterdam-repricings-v3.1.0/opcodes_tracing-stateful-perf-devnet-3.json


  container_runtime: podman
  client:
    config:
      rollback_strategy: container-recreate
      #rollback_strategy: container-checkpoint-restore
      #checkpoint_restore_strategy_options:
      #  tmpfs_threshold: "10g"
      #  tmpfs_max_size: "15g"
      #  wait_after_tcp_drop_connections: 10s
      #  restart_container: true
