runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: mainnet-24350000-osaka-compute
          chain: mainnet
          block: "24350000"
          test-type: compute
          context: repricing
          fork: osaka
      source:
        archive:
          file: https://github.com/NethermindEth/gas-benchmarks/releases/download/osaka-repricings-v1.0.0/generated-tests-compute-mainnet.tar.gz
          pre_run_steps:
            - "repricings_compute/mainnet/gas-bump.txt"
            - "repricings_compute/mainnet/funding.txt"
          steps:
            setup:
              - "repricings_compute/mainnet/setup/*.txt"
            test:
              - "repricings_compute/mainnet/testing/*.txt"
