runner:
  instances:
    # Besu
    - id: besu
      client: besu
      image: ethpandaops/besu:performance

    # Geth
    - id: geth
      client: geth
      image: ethpandaops/geth:master
      extra_args:
        - --debug.logslowblock=0

    # Nethermind
    - id: nethermind
      client: nethermind
      image: nethermindeth/nethermind:flat
      extra_args:
        - --config=mainnet
        - --FlatDb.Enabled=true # Enable FlatDB

    # Reth
    - id: reth
      client: reth
      image: ghcr.io/paradigmxyz/reth:nightly
      extra_args:
        - --engine.slow-block-threshold=0

    # Erigon
    - id: erigon
      client: erigon
      image: erigontech/erigon:main-latest
      environment:
        ERIGON_MAX_REORG_DEPTH: "512"
      extra_args:
        - --log.console.verbosity=debug
        - --fcu.background.commit=false
      bootstrap_fcu:
        enabled: true
        max_retries: 60
        backoff: 30s
