runner:
  instances:
    # Besu
    - id: besu
      client: besu
      image: ethpandaops/besu:macfarla-feature-execution-metrics-standardization-rebased
      extra_args:
        - --network-id=12159
        - --slow-block-threshold=0

    # Geth
    - id: geth
      client: geth
      image: ethpandaops/geth:master
      extra_args:
        - --cache=4096 # Geth sets this for mainnet, but not on perf-devnet-2
        - --networkid=12159
        - --debug.logslowblock=0

    # Nethermind
    - id: nethermind
      client: nethermind
      image: nethermindeth/nethermind:feature-execution-metrics
      extra_args:
        - --config=mainnet
        - --Init.NetworkId=12159
        - --FlatDb.Enabled=true # Enable FlatDB
        - --Blocks.SlowBlockThresholdMs=0

    # Reth
    - id: reth
      client: reth
      #image: ghcr.io/paradigmxyz/reth:nightly
      image: ethpandaops/reth:main
      extra_args:
        - --network-id=12159
        - --engine.slow-block-threshold=0
        - --engine.persistence-threshold=0
