runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-3-24358000-amsterdam-stateful
          chain: perf-devnet-3
          block: "24358000"
          test-type: stateful
          context: bal
          fork: amsterdam

      source:
        archive:
          file: https://github.com/NethermindEth/gas-benchmarks/actions/runs/25216010948/artifacts/6751115976
          pre_run_steps:
            - "gas-bump.txt"
            - "funding.txt"
          steps:
            setup:
              - "setup/*.txt"
            test:
              - "testing/*.txt"
      opcode_source:
        file: opcodes_tracing.json
        archive: https://github.com/NethermindEth/gas-benchmarks/actions/runs/25216010948/artifacts/6751112515

  container_runtime: podman
  client:
    config:
      rollback_strategy: container-recreate
      #rollback_strategy: container-checkpoint-restore
      #checkpoint_restore_strategy_options:
      #  tmpfs_threshold: "10g"
      #  tmpfs_max_size: "15g"
      #  wait_after_tcp_drop_connections: 10s
      #  restart_container: true
