global:
  log_level: info

builder:
  cleanup_on_start: true

runner:
  client_logs_to_stdout: true
  docker_network: benchmarkoor
  cleanup_on_start: true
  client:
    config:
      drop_memory_caches: "steps"

  live_reporting:
    enabled: true
    endpoint: https://benchmarkoor-api.core.ethpandaops.io
    token: ${API_INGEST_TOKEN}
    discovery_path: repricings/results
    interval: 1m
    timeout: 10s

  storage_probe:
    enabled: true
    file_size: 1GB   # size of the test file
    duration: 5s     # time of each workload
    io_depth: 64     # I/O operations in flight
