runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-3-24358000-stateful
          chain: perf-devnet-3
          block: "24358000"
          test-type: stateful
          context: repricing
          fork: osaka
      source:
        archive:
          file: https://github.com/NethermindEth/gas-benchmarks/releases/download/osaka-repricings-v1.0.0/generated-tests-compute-perf-devnet-3.tar.gz
          pre_run_steps:
            - "repricings_compute/perf-devnet-3/gas-bump.txt"
            - "repricings_compute/perf-devnet-3/funding.txt"
          steps:
            setup:
              - "repricings_compute/perf-devnet-3/setup/*.txt"
            test:
              - "repricings_compute/perf-devnet-3/testing/*.txt"

  # Use podman + checkpoint/restore via CRIU
  container_runtime: podman
  client:
    config:
      rollback_strategy: container-checkpoint-restore
      checkpoint_restore_strategy_options:
        tmpfs_threshold: "10g"
        tmpfs_max_size: "15g"
        wait_after_tcp_drop_connections: 10s
        restart_container: true
