runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-3-24358000-osaka-stateful
          chain: perf-devnet-3
          block: "24358000"
          test-type: stateful
          context: repricing
          fork: osaka
      source:
        archive:
          # file: https://github.com/NethermindEth/gas-benchmarks/releases/download/osaka-repricings-v1.1.0/generated-tests-stateful-perf-devnet-3.tar.gz
          # pre_run_steps:
          #   - "repricings_stateful/perf-devnet-3/gas-bump.txt"
          #   - "repricings_stateful/perf-devnet-3/funding.txt"
          # steps:
          #   setup:
          #     - "repricings_stateful/perf-devnet-3/setup/*.txt"
          #   test:
          #     - "repricings_stateful/perf-devnet-3/testing/*.txt"

          file: https://data.ethpandaops.io/benchmarkoor/osaka-repricings-stateful-jochem.tar.gz
          pre_run_steps:
            - "merged/gas-bump.txt"
            - "merged/funding.txt"
          steps:
            setup:
              - "merged/setup/*.txt"
            test:
              - "merged/testing/*.txt"
      opcode_source:
        file: https://data.ethpandaops.io/benchmarkoor/opcode_trace_results.json

  container_runtime: podman
  client:
    config:
      rollback_strategy: container-recreate
      #rollback_strategy: container-checkpoint-restore
      #checkpoint_restore_strategy_options:
      #  tmpfs_threshold: "10g"
      #  tmpfs_max_size: "15g"
      #  wait_after_tcp_drop_connections: 10s
      #  restart_container: true
