runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: perf-devnet-2-23861500-compute
          chain: perf-devnet-2
          block: "23861500"
          test-type: compute
      source:
        git:
          repo: https://github.com/nethermindeth/gas-benchmarks.git
          version: 4b421c294811ab9593d2f053ddfb4fd1fcba9aa0
          pre_run_steps:
            - repricings_compute/perf-devnet-2/gas-bump.txt
            - repricings_compute/perf-devnet-2/funding.txt
          steps:
            setup:
              - repricings_compute/perf-devnet-2/setup/*/
            test:
              - repricings_compute/perf-devnet-2/testing/*
            cleanup:
              - repricings_compute/perf-devnet-2/cleanup/*
