runner:
  benchmark:
    tests:
      metadata:
        labels:
          name: mainnet-24350000-compute
          chain: mainnet
          block: "24350000"
          test-type: compute
          context: repricing
      source:
        git:
          repo: https://github.com/nethermindeth/gas-benchmarks.git
          version: 7171589086b81960fcc8b1d76fa17203d4189334 # main
          pre_run_steps:
            - repricings_compute/mainnet/gas-bump.txt
            - repricings_compute/mainnet/funding.txt
          steps:
            setup:
              - repricings_compute/mainnet/setup/*
            test:
              - repricings_compute/mainnet/testing/*
